"""check for changes

Revision ID: 0f2534cea2fd
Revises: e8f9a0b1c2d3
Create Date: 2026-01-22 01:27:28.884769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2534cea2fd'
down_revision: Union[str, None] = 'e8f9a0b1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_drivers_location_active', table_name='drivers', postgresql_using='gist', postgresql_where='((is_active = true) AND (is_blocked = false))')
    op.drop_index('idx_drivers_route_seats_active', table_name='drivers', postgresql_where='(is_blocked = false)')
    op.alter_column('orders', 'pickup_lat',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=True,
               comment='Olish joyi - Latitude (None for text-only)',
               existing_comment='Olish joyi - Latitude')
    op.alter_column('orders', 'pickup_lon',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=True,
               comment='Olish joyi - Longitude (None for text-only)',
               existing_comment='Olish joyi - Longitude')
    op.drop_index('idx_orders_idempotency_key', table_name='orders')
    op.drop_index('idx_orders_route_status_created', table_name='orders')
    op.drop_index('idx_orders_trip_id_composite', table_name='orders', postgresql_where='(trip_id IS NOT NULL)')
    op.drop_index('idx_unique_pending_order_per_passenger', table_name='orders', postgresql_where="(status = 'PENDING'::order_status)")
    op.drop_constraint('uq_orders_idempotency_key', 'orders', type_='unique')
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.drop_index('idx_transaction_logs_created_desc', table_name='transaction_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transaction_logs_created_desc', 'transaction_logs', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.create_unique_constraint('uq_orders_idempotency_key', 'orders', ['idempotency_key'])
    op.create_index('idx_unique_pending_order_per_passenger', 'orders', ['passenger_id'], unique=True, postgresql_where="(status = 'PENDING'::order_status)")
    op.create_index('idx_orders_trip_id_composite', 'orders', ['trip_id', 'status'], unique=False, postgresql_where='(trip_id IS NOT NULL)')
    op.create_index('idx_orders_route_status_created', 'orders', ['route_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_orders_idempotency_key', 'orders', ['idempotency_key'], unique=False)
    op.alter_column('orders', 'pickup_lon',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=False,
               comment='Olish joyi - Longitude',
               existing_comment='Olish joyi - Longitude (None for text-only)')
    op.alter_column('orders', 'pickup_lat',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=False,
               comment='Olish joyi - Latitude',
               existing_comment='Olish joyi - Latitude (None for text-only)')
    op.create_index('idx_drivers_route_seats_active', 'drivers', ['current_route_id', 'available_seats', 'is_active'], unique=False, postgresql_where='(is_blocked = false)')
    op.create_index('idx_drivers_location_active', 'drivers', ['location'], unique=False, postgresql_using='gist', postgresql_where='((is_active = true) AND (is_blocked = false))')
    # ### end Alembic commands ###
