"""add_trip_model_and_order_trip_relationship

Revision ID: 4879ee18dbf7
Revises: 54d8fe8e46bb
Create Date: 2026-01-16 10:33:32.044867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4879ee18dbf7'
down_revision: Union[str, None] = '54d8fe8e46bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), autoincrement=True, nullable=False, comment='Trip ID'),
    sa.Column('driver_id', sa.BigInteger(), nullable=False, comment='Haydovchi ID'),
    sa.Column('route_id', sa.Integer(), nullable=False, comment='Marshrut ID'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='trip_status'), nullable=False, comment='Trip holati'),
    sa.Column('total_seats', sa.Integer(), nullable=False, comment="Jami o'rindiqlar (mashina sig'imi)"),
    sa.Column('available_seats', sa.Integer(), nullable=False, comment="Bo'sh o'rindiqlar"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Trip yaratilgan vaqt'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment="Safar boshlangan vaqt (yo'lga chiqqan)"),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Trip yakunlangan vaqt'),
    sa.Column('current_lat', sa.Numeric(precision=10, scale=8), nullable=True, comment='Joriy lat (GPS tracking)'),
    sa.Column('current_lon', sa.Numeric(precision=11, scale=8), nullable=True, comment='Joriy lon (GPS tracking)'),
    sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True, comment='Oxirgi location update vaqti'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index('idx_trips_created', 'trips', ['created_at'], unique=False)
    op.create_index('idx_trips_driver_status', 'trips', ['driver_id', 'status'], unique=False)
    op.create_index('idx_trips_route_status', 'trips', ['route_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.add_column('orders', sa.Column('trip_id', sa.Integer(), nullable=True, comment="Trip ID (NULL = trip yo'q)"))
    op.create_index(op.f('ix_orders_trip_id'), 'orders', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'trips', ['trip_id'], ['trip_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_trip_id'), table_name='orders')
    op.drop_column('orders', 'trip_id')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index('idx_trips_route_status', table_name='trips')
    op.drop_index('idx_trips_driver_status', table_name='trips')
    op.drop_index('idx_trips_created', table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
