"""add_phone_number

Revision ID: a45ea8e740a3
Revises: 45ac19888cb1
Create Date: 2026-01-12 16:34:21.177623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45ea8e740a3'
down_revision: Union[str, None] = '45ac19888cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_driver_ban_records_admin_id', table_name='driver_ban_records')
    op.add_column('drivers', sa.Column('phone_number', sa.String(length=20), nullable=False,server_default='UNKNOWN', comment='Telefon raqam (+998901234567)'))
    op.create_index(op.f('ix_drivers_phone_number'), 'drivers', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_phone_number'), table_name='drivers')
    op.drop_column('drivers', 'phone_number')
    op.create_index('ix_driver_ban_records_admin_id', 'driver_ban_records', ['admin_id'], unique=False)
    # ### end Alembic commands ###
