global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus o'zi
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Admin panel /metrics
  - job_name: "admin_panel"
    metrics_path: /metrics
    static_configs:
      - targets: ["admin_panel:8000"]

  # Server resurslari (node_exporter)
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  # Redis (redis_exporter)
  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]

  # Flower (Celery monitoring) - agar metrics yoqilgan bo'lsa
  - job_name: "flower"
    metrics_path: /metrics
    static_configs:
      - targets: ["flower:5555"]
